
name: cicd
on: 
  push:
    branches: 
      - main
jobs: 
  build and deploy:
    runs on: [ ubuntu:latest ]
    steps: 
      - name: Checkout Source
        uses: action/checkout@v4
      - name: Setup node
        uses: action/setup-node@v4
          with:
            node-version: 20
      - name: Install dependencies
        run: npm insatall
      - name: Generate Deployment Package
        run: zip -r testapp.zip .
      - name: Deploy to EB
          uses: einaregilsson/beanstalk-deploy@v22
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: nodejsapp
            environment_name: Nodejsapp-env
            version_label: ${{ github.sha }}
            region: ap-south-1
            deployment_package: testapp.zip
     
